Update and rename read_vmd_from_private_repo.yml to install_vmd_and_run_tests.yml

diff --git a/.github/workflows/install_vmd_and_run_tests.yml b/.github/workflows/install_vmd_and_run_tests.yml
--- a/.github/workflows/install_vmd_and_run_tests.yml
+++ b/.github/workflows/install_vmd_and_run_tests.yml
@@ -1,4 +1,4 @@
-name: Fetch, Build, Cache, and Verify VMD
+name: VMD installation and nougat testing
 
 on:
   push:
@@ -33,6 +33,18 @@ jobs:
             flex \
             bison \
             git
+
+      - name: Set up Python 3.11
+        uses: actions/setup-python@v3
+        with:
+          python-version: "3.11"
+      
+      - name: Install Python dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install numpy matplotlib
+          pip install pytest
+          pip install ./python/
 
       # Step 1: Generate GitHub App token
       - name: Generate GitHub App token
@@ -100,3 +112,22 @@ jobs:
           else
             echo "VMD installation verified successfully."
           fi
+
+      # Step 8: Generate new values for regression testing
+      - name: Generate new values for regression testing
+        run: |
+          cd $GITHUB_WORKSPACE/testing_materials/
+          echo "Running polarDensityBin.tcl on test systems in preparation for regression testing."
+          #vmd -dispdev none -e ./run_nougat_test.tcl 2>&1 | tee ./nougat_test_outputs.log
+          #if grep -q -e "can't" -e "couldn't" ./nougat_test_outputs.log
+          #then
+          #  echo "An error occurred when running nougat.tcl on the test systems"
+          #  exit 1
+          #fi
+
+      # Step 11: Regression testing
+      - name: Regression testing
+        run: |
+          cd $GITHUB_WORKSPACE/testing_materials/
+          echo "Regression testing start"
+          #python3 -m pytest ./tests/
