turning on tests

diff --git a/.github/workflows/install_vmd_and_run_tests.yml b/.github/workflows/install_vmd_and_run_tests.yml
--- a/.github/workflows/install_vmd_and_run_tests.yml
+++ b/.github/workflows/install_vmd_and_run_tests.yml
@@ -118,16 +118,16 @@ jobs:
         run: |
           cd $GITHUB_WORKSPACE/test_files/
           echo "Running polarDensityBin.tcl on test systems in preparation for regression testing."
-          #vmd -dispdev none -e ./run_dta_regr_test.tcl 2>&1 | tee ./dta_regr_test_outputs.log
-          #if grep -q -e "can't" -e "couldn't" ./dta_regr_test_outputs.log
-          #then
-          #  echo "An error occurred when running polarDensityBin.tcl on the test systems"
-          #  exit 1
-          #fi
+          vmd -dispdev none -e ./run_dta_regr_test.tcl 2>&1 | tee ./dta_regr_test_outputs.log
+          if grep -q -e "can't" -e "couldn't" ./dta_regr_test_outputs.log
+          then
+            echo "An error occurred when running polarDensityBin.tcl on the test systems"
+            exit 1
+          fi
 
       # Step 11: Regression testing
       - name: Regression testing
         run: |
           cd $GITHUB_WORKSPACE/test_files/
           echo "Regression testing start"
-          #python3 -m pytest ./tests/
+          python3 -m pytest ./tcl_regr_test.py
